<?php
session_start();
include "../connect.php";

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'nurse') {
    header("Location: ../index.php");
    exit();
}
require_once __DIR__ . '/../libs/dompdf/autoload.inc.php'; 
use Dompdf\Dompdf;

$start_date = $_GET['start_date'] ?? date('Y-m-01');
$end_date   = $_GET['end_date'] ?? date('Y-m-d');

$totalVisits = mysqli_fetch_assoc(mysqli_query($conn,"
    SELECT COUNT(*) AS total 
    FROM treatments 
    WHERE treatment_date BETWEEN '$start_date' AND '$end_date'
"))['total'];

$totalStudents = mysqli_fetch_assoc(mysqli_query($conn,"
    SELECT COUNT(DISTINCT student_id) AS total 
    FROM treatments 
    WHERE treatment_date BETWEEN '$start_date' AND '$end_date'
"))['total'];

$totalReferrals = mysqli_fetch_assoc(mysqli_query($conn,"
    SELECT COUNT(*) AS total 
    FROM treatments 
    WHERE category='Referral'
    AND treatment_date BETWEEN '$start_date' AND '$end_date'
"))['total'];

$categoryQuery = mysqli_query($conn,"
    SELECT category, COUNT(*) AS total 
    FROM treatments 
    WHERE treatment_date BETWEEN '$start_date' AND '$end_date'
    GROUP BY category
");

$labels = [];
$data = [];

while($row = mysqli_fetch_assoc($categoryQuery)){
    $labels[] = $row['category'];
    $data[] = $row['total'];
}

$labels_json = json_encode($labels);
$data_json = json_encode($data);

$trendQuery = mysqli_query($conn,"
    SELECT medication, COUNT(*) as total
    FROM treatments
    WHERE treatment_date BETWEEN '$start_date' AND '$end_date'
    GROUP BY treatment_date
");

$trend_labels = [];
$trend_data = [];

while($row = mysqli_fetch_assoc($trendQuery)){
    $trend_labels[] = $row['treatment_date'];
    $trend_data[] = $row['total'];
}

$trend_labels_json = json_encode($trend_labels);
$trend_data_json = json_encode($trend_data);

$html = '
<html>
<head>
<style>
body{font-family: Arial; font-size:12px;}
h1{color:#0b7285;}
table{width:100%; border-collapse: collapse; margin-top:10px;}
th,td{border:1px solid #ccc; padding:6px; text-align:left;}
th{background:#f0f0f0;}
.summary{margin-top:15px;}
.card{display:inline-block; width:30%; padding:10px;}
.footer{text-align:center; margin-top:20px; font-size:10px;}
</style>
</head>
<body>

<h1>EduHealth System</h1>
<h3>Nurse Clinical Report</h3>
<p>From: '.$start_date.' To: '.$end_date.'</p>

<div class="summary">
<div class="card"><b>Total Visits:</b> '.$totalVisits.'</div>
<div class="card"><b>Students Treated:</b> '.$totalStudents.'</div>
<div class="card"><b>Referrals:</b> '.$totalReferrals.'</div>
</div>

<h3>Detailed Records</h3>
<table>
<tr>
<th>Date</th>
<th>Student</th>
<th>Category</th>
<th>Diagnosis</th>
<th>Treatment</th>
</tr>
';

$records = mysqli_query($conn,"
    SELECT s.full_name, t.category, t.diagnosis, t.medication
    FROM treatments t
    JOIN students s ON t.student_id = s.student_id
    WHERE t.treatment_date BETWEEN '$start_date' AND '$end_date'
");

while($r = mysqli_fetch_assoc($records)){
    $html .= '<tr>
        <td>'.$r['full_name'].'</td>
        <td>'.$r['category'].'</td>
        <td>'.$r['diagnosis'].'</td>
        <td>'.$r['medication'].'</td>
    </tr>';
}

$html .= '
</table>

<div class="footer">
Generated by EduHealth System | '.date("Y").'
</div>

</body>
</html>
';

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("Nurse_Report.pdf", ["Attachment" => false]);
exit();
?>